siteurl: https://tedt.org
#baseurl: https://tedt.org/

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']

timezone: America/Los_Angeles

owner:
  disqus-shortname: tedtschopp

# Varaibles that will be used elsewhere
# Use {% assign author = site.authors[page.author] %} to get author which author
authors:
  tschopp:
    name: Ted Tschopp
    url: https://tedt.org/
    avatar: https://tedt.org/img/thumb3.jpg
    givenname: Ted
    familyname: Tschopp
    othernames: Þeodor Tʃopp | टेड चप | Фёдор Тшёп | تِد چاپ | Թէտ Չըփ | Ted Çeöp | தெட் சுப்
    biography:
      - I am the enterprise technology architect focused on digital and automation portfolios at Southern California Edison(SCE), one of the United States' largest investor-owned utilities with a service territory of over 50,000 square miles consisting of 430 cities and home to nearly 14 million people. In this role I am responsible for providing major stake holders, executives, and senior management with strategic and actionable guidance focusing on the maturity and technical issues and risks associated with Web, Mobile, Social, and Automation ecosystems. I have been at SCE for over a decade.
      - Before working at Edison, I owned my own business which was featured in Wired Magazine. I founded the largest community website focused on the works of J.R.R. Tolkien. Prior to this I worked in for a market research company focusing on the automotive industry.
      - I love working in technology as it provides me with the opportunity to watch the future unfold. Some of the things I have worked on were considered science-fiction when I was in school. This means I get to work on hard problems with brilliant people using complex and cool tools.
    email: ted@tschopp.org
    phonenumber: 
    keybaseio_username: tedtschopp
    twitter_username: TedTschopp
    github_username: TedTschopp
    linkedin_username: tedtschopp
    facebook_username: ted.tschopp
    google_username: TedTschopp
    youtube_username: TedTschopp
    pinterest_username: TedTschopp
    reddit_username: tedtschopp
    instagram_username: tedtschopp
    quora_username: Ted-Tschopp
    indiewebcamp_username: Www.tedt.org
    mastadon_username: TedT@twit.social

author:
  name: Ted Tschopp
  url: https://tedt.org/
  avatar: https://tedt.org/img/thumb3.jpg
  givenname: Ted
  familyname: Tschopp
  othernames: Þeodor Tʃopp | टेड चप | Фёдор Тшёп | تِد چاپ | Թէտ Չըփ | Ted Çeöp | தெட் சுப்
  biography:
    - I am the enterprise technology architect focused on digital and automation portfolios at Southern California Edison(SCE), one of the United States' largest investor-owned utilities with a service territory of over 50,000 square miles consisting of 430 cities and home to nearly 14 million people. In this role I am responsible for providing major stake holders, executives, and senior management with strategic and actionable guidance focusing on the maturity and technical issues and risks associated with Web, Mobile, Social, and Automation ecosystems. I have been at SCE for over a decade.
    - Before working at Edison, I owned my own business which was featured in Wired Magazine. I founded the largest community website focused on the works of J.R.R. Tolkien. Prior to this I worked in for a market research company focusing on the automotive industry.
    - I love working in technology as it provides me with the opportunity to watch the future unfold. Some of the things I have worked on were considered science-fiction when I was in school. This means I get to work on hard problems with brilliant people using complex and cool tools.
  email: ted@tschopp.org
  phonenumber: 
  keybaseio_username: tedtschopp
  twitter_username: TedTschopp
  github_username: TedTschopp
  linkedin_username: tedtschopp
  facebook_username: ted.tschopp
  google_username: TedTschopp
  youtube_username: TedTschopp
  pinterest_username: TedTschopp
  reddit_username: tedtschopp
  instagram_username: tedtschopp
  quora_username: Ted-Tschopp
  indiewebcamp_username: Www.tedt.org
  mastadon_username: TedT@twit.social


# First Name / Given Name / Common Name
givenname: Ted

#Family Name
familyname: Tschopp

#Other Names
othernames: >
  Þeodor Tʃopp | टेड चप | Фёдор Тшёп | تِد چاپ | Թէտ Չըփ | Ted Çeöp | தெட் சுப்

#Biography 
biography:
  - I am the enterprise technology architect focused on digital and automation portfolios at Southern California Edison(SCE), one of the United States' largest investor-owned utilities with a service territory of over 50,000 square miles consisting of 430 cities and home to nearly 14 million people. In this role I am responsible for providing major stake holders, executives, and senior management with strategic and actionable guidance focusing on the maturity and technical issues and risks associated with Web, Mobile, Social, and Automation ecosystems. I have been at SCE for over a decade.
  - Before working at Edison, I owned my own business which was featured in Wired Magazine. I founded the largest community website focused on the works of J.R.R. Tolkien. Prior to this I worked in for a market research company focusing on the automotive industry.
  - I love working in technology as it provides me with the opportunity to watch the future unfold. Some of the things I have worked on were considered science-fiction when I was in school. This means I get to work on hard problems with brilliant people using complex and cool tools.


# Verison
version: 1.0.0

email: ted@tschopp.org
phonenumber: 
keybaseio_username: tedtschopp
twitter_username: TedTschopp
github_username: TedTschopp
linkedin_username: tedtschopp
facebook_username: ted.tschopp
google_username: TedTschopp
youtube_username: TedTschopp
pinterest_username: TedTschopp
reddit_username: tedtschopp
instagram_username: tedtschopp
quora_username: Ted-Tschopp
indiewebcamp_username: Www.tedt.org
mastadon_username: TedT@twit.social

# Other Ssytems to integrate
dropbox:
evernote:

rabbitmq: 
angellist: tedtschopp

fitbit: //www.fitbit.com/user/242JHZ
foursquare: //foursquare.com/theothesilly
flickr: 
force:
goodreads: //www.goodreads.com/TedTschopp
instagram: www.instagram.com/tedtschopp/
meetup: //www.meetup.com/members/45846/
runkeeper: //runkeeper.com/user/TedTschopp
soundcloud: //soundcloud.com/ted-tschopp
tripit: //www.tripit.com/people/TedTschopp
twitch: https://www.twitch.tv/theothesilly
tumblr:
vimeo: //vimeo.com/tedtschop
windowslive:
xboxlive:
Steam: //steamcommunity.com/id/theothesilly/
withings:
yammer:
gravatar: 



# The Logo of the site
logo: https://tedt.org/img/android-chrome-512x512.png

# The title tag of the site
title: Ted Tschopp

#description of the site for meta tags
description: Discover who Ted Tschopp is.  My homepage has links to all the other things I have around the internet

# Site's name
name: Ted Tschopp's Homepage

#Locality
locality: Los Angeles
region: California
country: United States of America

# Verification Keys
pinterest_domain_verify: 98d8bdfab96a340e5a4f03f7a4303f0e
google_custom_search: 003027838407468454148:ddtovg0fltc
facebook_app_id: 1939132006351436



# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # FACEBOOK
  - Name: Facebook
    URL: https://www.facebook.com
    Username: ted.tschopp
    Color: '#3b5998'
    Icon-Class: fab fa-facebook

    # INSTAGRAM
    # - Name: Instagram
    # URL: https://www.instagram.com
    # Username: harsh98trivedi
    # Color: '#DD2A7B'
    # Icon-Class: fab fa-instagram

    # TWITTER
  - Name: Twitter
    URL: https://twitter.com
    Username: TedTschopp
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter

    # CLUBHOUSE
    # - Name: Clubhouse
    # URL: https://www.clubhouse.com
    # Username: '@harsh98trivedi'
    # Color: '#f1c40f'
    # Icon-Class: fas fa-hand-paper -mt-0.5
    
    # LINKEDIN
  - Name: LinkedIn
    URL: https://www.linkedin.com/in
    Username: harsh98trivedi
    Color: '#2867B2'
    Icon-Class: fab fa-linkedin-in

    # YOUTUBE
    # - Name: YouTube
    # URL: https://www.youtube.com/channel
    # Username: UCS3zvA_2r1iGT7MB3NVCGAw
    # Color: '#ff0000'
    # Icon-Class: fab fa-youtube

    # GITHUB
  - Name: GitHub
    URL: http://github.com
    Username: TedTschopp
    Color: '#6e5494'
    Icon-Class: fab fa-github

    # EMAIL
  - Name: Email
    URL: 'mailto:ted@tedt.org'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'

    # TWITCH
    # - Name: Twitch
    # URL: 'https://twitch.tv'
    # Username: harsh98trivedi
    # Icon-Class: fab fa-twitch
    # Color: '#9147fe'
    # Text_Color: '#ffffff'

    # VIMEO
  - Name: Vimeo
    URL: 'https://vimeo.com'
    Username: TedTschopp
    Icon-Class: fab fa-vimeo-v
    Color: '#1ab7ea'
    Text_Color: '#ffffff'

    # MESSENGER
  - Name: Messenger
    URL: https://m.me
    Username: TedTschopp
    Color: '#006AFF'
    Icon-Class: fab fa-facebook-messenger

    # REDDIT
  - Name: Reddit
    URL: http://reddit.com/u
    Username: TedTschopp
    Color: '#FF4500'
    Icon-Class: fab fa-reddit-alien

  #   # WHATSAPP
  # - Name: WhatsApp
  #   URL: https://wa.me
  #   Username: '+1123456789'
  #   Color: '#25d366'
  #   Icon-Class: fab fa-whatsapp

  #  # TELEGRAM
  #- Name: Telegram
  #  URL: http://telegram.me
  #  Username: theharshtrivedi
  #  Color: '#0088cc'
  #  Icon-Class: fab fa-telegram-plane

  #  # SNAPCHAT
  #- Name: Snapchat
  #  URL: https://www.snapchat.com/add
  #  Username: 'harsh98trivedi'
  #  Color: '#FFFC00'
  #  Text_Color: '#000000'
  #  Icon-Class: fab fa-snapchat-ghost

    # STEAM
  - Name: Steam
    URL: https://steamcommunity.com/id
    Username: 'TedTschopp'
    Color: '#66c0f4'
    Text_Color: '#000000'
    Icon-Class: fab fa-steam

  #   # DISCORD
  # - Name: Discord
  #   URL: 'https://discord.gg'
  #   Username: 
  #   Icon-Class: fab fa-discord
  #   Color: '#5865F2'
  #   Text_Color: '#ffffff'

  #  # PINTEREST
  #- Name: Pinterest
  #  URL: https://pinterest.com
  #  Username: 'harsh98trivedi'
  #  Color: '#E60023'
  #  Icon-Class: fab fa-pinterest

  #  # BEHANCE
  #- Name: Behance
  #  URL: https://www.behance.net
  #  Username: harsh98trivedi
  #  Color: '#1769ff'
  #  Icon-Class: fab fa-behance

  #   # DRIBBBLE
  # - Name: Dribbble
  #   URL: https://dribbble.com
  #   Username: 
  #   Color: '#ea4c89'
  #   Icon-Class: fab fa-dribbble

  #  # DEVIANTART
  #- Name: DeviantArt
  #  URL: https://www.deviantart.com
  #  Username: harshtrivedi
  #  Icon-Class: fab fa-deviantart
  #  Color: '#05CC46'
  #  Text_Color: '#ffffff'

  #  # FIGMA
  # - Name: Figma
  #  URL: https://www.figma.com
  #  Username: '@harshtrivedi'
  #  Icon-Class: fab fa-figma
  #  Color: '#ff2865'
  #  Text_Color: '#ffffff'

  #  # SPOTIFY
  #- Name: Spotify
  #  URL: http://open.spotify.com/user
  #  Username: 314ihryk3edvtusti6il3oy3x5da
  #  Color: '#1DB954'
  #  Icon-Class: fab fa-spotify

  #  # SOUNDCLOUD
  #- Name: SoundCloud
  #  URL: https://www.soundcloud.com
  #  Username: harsh98trivedi
  #  Color: '#FE5000'
  #  Icon-Class: fab fa-soundcloud

  #    # TIKTOK
  # - Name: TikTok
  #   URL: https://www.tiktok.com
  #   Username: 
  #   Color: '#FE2C55'
  #   Icon-Class: fab fa-tiktok

    # MEDIUM
  - Name: Medium
    URL: 'https://medium.com'
    Username: '@TedTschopp'
    Icon-Class: fab fa-medium-m
    Color: '#00ab6c'
    Text_Color: '#ffffff'

    # DEV.TO
  - Name: Dev.to
    URL: 'https://dev.to'
    Username: tedtschopp
    Icon-Class: fab fa-dev
    Color: '#ffffff'
    Text_Color: '#000000'

  #   # TUMBLR
  # - Name: Tumblr
  #   URL: https://www.tumblr.com
  #   Username: 
  #   Color: '#35465c'
  #   Icon-Class: fab fa-tumblr

  # BUY ME A COFFEE
  - Name: BuyMeACoffee
    URL: 'https://buymeacoffee.com'
    Username: TedT
    Icon-Class: fas fa-mug-hot
    Color: '#FFDD00'
    Text_Color: '#000000'

  #  # CUSTOM LINK
  #- Name: Blog
  #  URL: https://harsh98trivedi.github.io/blog
  #  Icon-Class: fas fa-link
  #  Color: '#ffb142'
  #  Text_Color: '#ffffff'

  #- Name: Links
  #  URL: https://github.com/harsh98trivedi/links
  #  Icon-Class: fas fa-link
  #  Color: '#d94869'
  #  Text_Color: '#ffffff'