# markdown: kramdown
plugins:
  - jekyll-redirect-from

#baseurl: https://tedt.org/
siteurl: https://tedt.org

#description of the site for meta tags
description: "Technology, theology, and creativity converge in this insightful exploration by Ted Tschopp, who navigates the intricate relationship between these topics in the digital age. From dissecting how technology is reshaping religious practices and ethics to sharing cutting-edge trends in UI/UX design, collaboration tools, and digital storytelling, the author provides a multifaceted analysis. Written with a unique and engaging blend of humor, reflection, and curiosity, this work invites readers to ponder and discuss these connections, offering a contemplative lens on modern innovation and cultural evolution."

keywords: "technology, theology, creativity, religion, digital age, UI/UX, collaboration tools, storytelling"

# Permalink 
permalink: /:categories/:title

# First Name / Given Name / Common Name
givenname: Ted

#Family Name
familyname: Tschopp

#Other Names
othernames: >
  √ûeodor T Éopp | ‡§ü‡•á‡§° ‡§ö‡§™ | –§—ë–¥–æ—Ä –¢—à—ë–ø | ÿ™ŸêÿØ ⁄ÜÿßŸæ | ‘π’ß’ø ’â’®÷É | Ted √áe√∂p | ‡Æ§‡ØÜ‡Æü‡Øç ‡Æö‡ØÅ‡Æ™‡Øç

#Biography 
biography:
  - I am the enterprise architect at Southern California Edison (SCE), serving over 20 million people across 430 cities and 50,000 square miles. In my role, I offer strategic guidance on all software and products developed in IT to executives, senior leadership, and business stakeholders, drawing on my 25 years of experience at SCE.
  - Before joining Edison, I owned a business featured in Wired Magazine.  I founded the largest J.R.R. Tolkien community website. Earlier, I worked in market research for the automotive industry.
  - I love working in technology as it provides me with the opportunity to watch the future unfold. Some of the things I have worked on were considered science-fiction when I was in school. This means I get to work on hard problems with brilliant people using complex and cool tools.

# The Logo of the site
logo: https://tedt.org/img/Site-Logo.png
title_image: https://tedt.org/img/Site-Logo.png
title-image-alt: 'Logo for Ted Tschopp'

# The title tag of the site
title: Ted Tschopp

# Subtitle
subtitle: Exploring the Theology of the Digital Age Through Creativity, Ethics, and Faith.

# Site's name
name: Ted Tschopp's Homepage

#Locality
locality: Los Angeles
region: California
country: United States of America

# Verification Keys
pinterest_domain_verify: 98d8bdfab96a340e5a4f03f7a4303f0e
google_custom_search: 003027838407468454148:ddtovg0fltc
facebook_app_id: 1939132006351436

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']

wlinks:
  symbol: #
  check: complete
  title: Anchor

# Mastodon Settings for Comments

mastodon_comments:
  host: tschopp.net
  username: Ted

timezone: America/Los_Angeles

collections:
  GammaWorld:
   output: true
   permalink: /:collection/:title

# Varaibles that will be used elsewhere
# Use {% assign author = site.authors[page.author] %} to get author which author
authors:
  tschopp:
    name: Ted Tschopp
    url: https://tedt.org/
    avatar: https://secure.gravatar.com/avatar/a76b4d6291cecb3a738896a971bfb903?s=512&d=mp&r=g
    givenname: Ted
    familyname: Tschopp
    othernames: √ûeodor T Éopp | ‡§ü‡•á‡§° ‡§ö‡§™ | –§—ë–¥–æ—Ä –¢—à—ë–ø | ÿ™ŸêÿØ ⁄ÜÿßŸæ | ‘π’ß’ø ’â’®÷É | Ted √áe√∂p | ‡Æ§‡ØÜ‡Æü‡Øç ‡Æö‡ØÅ‡Æ™‡Øç
    biography:
      - I am the enterprise architect focused on the IT portfolio, Product Engineering, and Product Development at Southern California Edison(SCE), one of the United States' largest investor-owned utilities with a service territory of over 50,000 square miles consisting of 430 cities and home to nearly 14 million people. In this role I am responsible for providing major stake holders, executives, and senior management with strategic and actionable guidance focusing on the maturity and technical issues and risks associated with the IT portfolio and how we Engineer and Construct solutions for our business partners. I have been at SCE for over 20 years.
      - Before working at Edison, I owned my own business which was featured in Wired Magazine. I founded the largest community website focused on the works of J.R.R. Tolkien. Prior to this I was the Director of Technical Services for a market research company focused on the automotive industry.
      - I love working in technology as it provides me with the opportunity to watch the future unfold. Some of the things I have worked on were considered science-fiction when I was in school. This means I get to work on hard problems with brilliant people using complex and cool tools.
    email: ted@tschopp.org
    phonenumber: 
    keybaseio_username: tedtschopp
    twitter_username: TedTschopp
    github_username: TedTschopp
    linkedin_username: tedtschopp
    facebook_username: ted.tschopp
    google_username: TedTschopp
    youtube_username: TedTschopp
    pinterest_username: TedTschopp
    reddit_username: tedtschopp
    instagram_username: tedtschopp
    quora_username: Ted-Tschopp
    indiewebcamp_username: Www.tedt.org
    mastadon_username: TedT@twit.social
    threads_username: tedtschopp

author:
  name: Ted Tschopp
  url: https://tedt.org/
  avatar: https://secure.gravatar.com/avatar/a76b4d6291cecb3a738896a971bfb903?s=512&d=mp&r=g
  givenname: Ted
  familyname: Tschopp
  othernames: √ûeodor T Éopp | ‡§ü‡•á‡§° ‡§ö‡§™ | –§—ë–¥–æ—Ä –¢—à—ë–ø | ÿ™ŸêÿØ ⁄ÜÿßŸæ | ‘π’ß’ø ’â’®÷É | Ted √áe√∂p | ‡Æ§‡ØÜ‡Æü‡Øç ‡Æö‡ØÅ‡Æ™‡Øç
  biography:
    - I am the enterprise technology architect focused on digital and automation portfolios at Southern California Edison(SCE), one of the United States' largest investor-owned utilities with a service territory of over 50,000 square miles consisting of 430 cities and home to nearly 14 million people. In this role I am responsible for providing major stake holders, executives, and senior management with strategic and actionable guidance focusing on the maturity and technical issues and risks associated with Web, Mobile, Social, and Automation ecosystems. I have been at SCE for over a decade.
    - Before working at Edison, I owned my own business which was featured in Wired Magazine. I founded the largest community website focused on the works of J.R.R. Tolkien. Prior to this I worked in for a market research company focusing on the automotive industry.
    - I love working in technology as it provides me with the opportunity to watch the future unfold. Some of the things I have worked on were considered science-fiction when I was in school. This means I get to work on hard problems with brilliant people using complex and cool tools.
  email: ted@tschopp.org
  phonenumber: 
  keybaseio_username: tedtschopp
  twitter_username: TedTschopp
  github_username: TedTschopp
  linkedin_username: tedtschopp
  facebook_username: ted.tschopp
  google_username: TedTschopp
  youtube_username: TedTschopp
  pinterest_username: TedTschopp
  reddit_username: tedtschopp
  instagram_username: tedtschopp
  quora_username: Ted-Tschopp
  indiewebcamp_username: Www.tedt.org
  mastadon_username: TedT@twit.social
  threads_username: tedtschopp
#  google_username: TedTschopp





# Verison
version: 1.5.0

email: ted@tschopp.org
phonenumber: 
indiewebcamp_username: Www.tedt.org                                    # Done
github_username: TedTschopp                                            # Done
quora_username: Ted-Tschopp                                            # Done
pinterest_username: TedTschopp                                         # Done
youtube_username: TedTschopp                                           # done
linkedin_username: tedtschopp                                          # Done
facebook_username: ted.tschopp                                         # Done
reddit_username: tedtschopp                                            # Done
twitter_username: TedTschopp                                           # Done
threads_username: TedTschopp@threads.net                               # Done
mastadon_username: TedT@twit.social                                    # Done
instagram_username: tedtschopp                                         # Done
foursquare: //foursquare.com/tedtschopp                                # Done
goodreads: //www.goodreads.com/TedTschopp                              # Done
instagram: www.instagram.com/tedtschopp/                               # Done
meetup: //www.meetup.com/members/45846/                                # Done
soundcloud: //soundcloud.com/ted-tschopp                               # Done
twitch: https://www.twitch.tv/tedtschopp                               # Done
tumblr: https://www.tumblr.com/blog/tedtschopp                         # Done
vimeo: //vimeo.com/tedtschop                                           # Done
xboxlive: https://account.xbox.com/en-us/profile?gamertag=TheoTheSilly # Done
Steam: //steamcommunity.com/id/theothesilly/                           # Done
keybaseio_username: tedtschopp                                         # Done  


fitbit: //www.fitbit.com/user/242JHZ
runkeeper: //runkeeper.com/user/TedTschopp                            
angellist: tedtschopp
dropbox:
evernote:
flickr: 
force:
windowslive:
withings:
yammer:
gravatar: 
rabbitmq: 
# google_username: TedTschopp


# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK

    # Midjourney
  - Name: Midjourney
    URL: https://www.midjourney.com/app/users/074b5e95-1e8a-465f-9a7f-921e11670eb5/
    Icon-Class: fa-solid fa-sailboat
    Color: '#19202c'
    Text_Color: '#f8fafb'
    # BlueSky
  - Name: BlueSky
    URL: https://bsky.app/profile/
    Username: tedt.org
    Icon-Class: fa-solid fa-cloud
    Color: '#0085FF'
    Text_Color: '#ffffff'
    # Threads
  - Name: Threads
    URL: https://threads.net
    Username: '@TedTschopp'
    Icon-Class: fa-brands fa-threads
    Color: '#000000'
    Text_Color: '#ffffff'
    # Mastodon
  - Name: Mastodon
    URL: https://twit.social
    Username: '@TedT'
    Icon-Class: fa-brands fa-mastodon
    Color: '#595aff'
    Text_Color: '#ffffff'
    # LINKEDIN
  - Name: LinkedIn
    URL: https://www.linkedin.com/in
    Username: tedtschopp
    Color: '#2867B2'
    Icon-Class: fab fa-linkedin-in
    # GITHUB
  - Name: GitHub
    URL: http://github.com
    Username: TedTschopp
    Color: '#6e5494'
    Icon-Class: fab fa-github
    # EMAIL
  - Name: Email
    URL: 'mailto:ted@tedt.org'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'
    # MEDIUM
  - Name: Medium
    URL: 'https://medium.com'
    Username: '@TedTschopp'
    Icon-Class: fab fa-medium-m
    Color: '#00ab6c'
    Text_Color: '#ffffff'
    # VIMEO
  - Name: Vimeo
    URL: 'https://vimeo.com'
    Username: TedTschopp
    Icon-Class: fab fa-vimeo-v
    Color: '#1ab7ea'
    Text_Color: '#ffffff'
    # BUY ME A COFFEE
  - Name: BuyMeACoffee
    URL: 'https://buymeacoffee.com'
    Username: TedT
    Icon-Class: fas fa-mug-hot
    Color: '#FFDD00'
    Text_Color: '#000000'
    # REDDIT
  - Name: Reddit
    URL: http://reddit.com/u
    Username: TedTschopp
    Color: '#FF4500'
    Icon-Class: fab fa-reddit-alien
    # GOODREADS
  - Name: Goodreads
    URL: https://www.goodreads.com/user/show/856383-ted-tschopp
    Icon-Class: fab fa-goodreads
    Color: '#e9e5cd'
    Text_Color: '#553b08'
    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: TedTschopp
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram
    # Meetup
  - Name: Meetup
    URL: 'https://www.meetup.com/members/45846/'
    Icon-Class: fa-brands fa-meetup
    Color: '#ED1C40'
    Text_Color: '#FFFFFF'
    # SOUNDCLOUD
  - Name: SoundCloud
    URL: https://www.soundcloud.com
    Username: ted-tschopp
    Color: '#FE5000'
    Icon-Class: fab fa-soundcloud
    # TWITCH
  - Name: Twitch
    URL: 'https://twitch.tv'
    Username: tedtschopp
    Icon-Class: fab fa-twitch
    Color: '#9147fe'
    Text_Color: '#ffffff'
    # TUMBLR
  - Name: Tumblr
    URL: https://www.tumblr.com/blog
    Username: tedtschopp
    Color: '#35465c'
    Icon-Class: fab fa-tumblr
    # DEV.TO
  - Name: Dev.to
    URL: 'https://dev.to'
    Username: tedtschopp
    Icon-Class: fab fa-dev
    Color: '#ffffff'
    Text_Color: '#000000'
    # STEAM
  - Name: Steam
    URL: https://steamcommunity.com/id
    Username: 'theothesilly'
    Color: '#66c0f4'
    Text_Color: '#000000'
    Icon-Class: fab fa-steam
    # TWITTER
  - Name: ùïè
    URL: https://twitter.com
    Username: TedTschopp
    Color: '#1DA1F2'
    # FACEBOOK
  - Name: Facebook
    URL: https://www.facebook.com
    Username: ted.tschopp
    Color: '#3b5998'
    Icon-Class: fab fa-facebook
    # MESSENGER
  - Name: Messenger
    URL: https://m.me
    Username: TedTschopp
    Color: '#006AFF'
    Icon-Class: fab fa-facebook-messenger
    # XBOX
  - Name: xBox
    URL: https://account.xbox.com/en-us/profile?gamertag=
    Username: TheoTheSilly
    Icon-Class: fa-brands fa-xbox
    Color: '#107C10'
    Text_Color: '#FFFFFF'
    # YOUTUBE
  - Name: YouTube
    URL: https://www.youtube.com/channel
    Username: UC4Q8pXroTVyXrIxg2u82pwg
    Color: '#ff0000'
    Icon-Class: fab fa-youtube
    # Foursquare
  - Name: Foursquare
    URL: https://foursquare.com
    Username: tedtschopp
    Icon-Class: fab fa-foursquare
    Color: '#0072b1'
    Text_Color: '#eeebac'
    # Quora
  - Name: Quora
    URL: https://www.quora.com/profile
    Username: Ted-Tschopp
    Icon-Class: fa fa-quora
    Color: '#ffffff'
    Text_Color: '#B92B27'
    # PINTEREST
  - Name: Pinterest
    URL: https://pinterest.com
    Username: 'tedtschopp'
    Color: '#E60023'
    Icon-Class: fab fa-pinterest
    # SNAPCHAT
  - Name: Snapchat
    URL: https://www.snapchat.com/add
    Username: 'TedTschopp'
    Color: '#FFFC00'
    Text_Color: '#000000'
    Icon-Class: fab fa-snapchat-ghost
    # Keybase
  - Name: Keybase
    URL: https://keybase.io
    Username: 'tedtschopp'
    Color: '#4866b0'
    Text_Color: '#ffffff'
    Icon-Class: fa-brands fa-keybase
    # Indie Web Camp
  - Name: Indieweb
    URL: https://indieweb.org/User:Www.tedt.org
    Icon-Class: fa-solid fa-blog
    Color: '#000000'
    Text_Color: '#ffffff'
    # Homepage
  - Name: Blog
    URL: https://www.tedt.org
    Icon-Class: fas fa-home fa-lg fa-fw
    Color: '#000000'
    Text_Color: '#ffffff'

  #  # CUSTOM LINK
  #- Name: Blog
  #  URL: https://#
  #  Icon-Class: fas fa-link
  #  Color: '#ffb142'
  #  Text_Color: '#ffffff'

  #- Name: Links
  #  URL: https://#
  #  Icon-Class: fas fa-link
  #  Color: '#d94869'
  #  Text_Color: '#ffffff'



# hcard:
#   organization: Distribution
#   name: Jayne Cobb
# 
#   # email_type: office
#   # email_address: name@example.com
#   emails:
#     - type: office
#       address: name@example.com
# 
#   # phone_type: cell
#   # phone_number: 555-123-4567
#   phone_numbers:
#     - type: cell
#       number: 555-123-4567
# 
#     - type: office
#       number: 555-987-6543
# 
#   address:
#     street: 418 Code St.
#     extended: Suite 503       ## AKA suite, apartment, etc.
#     country_code: USA
#     country_name: United States of America
#     locality: Server Request  ## AKA city
#     region: ZZ                ## AKA state
#     postal_code: 12345        ## AKA zip
# 
#   # link_label: 'example'
#   # link_url: https://example.com
#   links:
#     - label: 'example one'
#       url: https://example.com
# 
#     - label: 'example two'
#       url: https://example.com
# 
#     - label: 'example three'
#       url: https://example.com
# 